name: Deploy Graph

on:
  pull_request:
    types: [opened, ready_for_review, synchronize]
  push:
    branches: [master]

jobs:
  deploy-dev:
    if: github.event_name == 'pull_request' && github.event.pull_request.draft == false
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
          - network: arbitrum-testnet
    steps:
      - uses: actions/checkout@v2
      - name: Install node
        uses: actions/setup-node@v1
        with:
          node-version: 14
      - name: Install
        run: yarn --frozen-lockfile
      - name: Prepare
        env:
          NETWORK: ${{ matrix.network }}
        run: yarn prepare:$NETWORK
      - name: Codegen
        env:
          NETWORK: ${{ matrix.network }}
        run: yarn codegen:$NETWORK
      - name: Test
        run: yarn test
      - name: Build
        env:
          NETWORK: ${{ matrix.network }}
        run: yarn build:$NETWORK
      - name: Authenticate
        env:
          GRAPH_ACCESS_TOKEN: ${{ secrets.GRAPH_ACCESS_TOKEN }}
        run: yarn graph auth --product hosted-service "$GRAPH_ACCESS_TOKEN"
      - name: Deploy to development
        run: yarn deploy:dev
  deploy-prod:
    if: github.event_name == 'push' && github.ref == 'refs/heads/master'
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
          - network: arbitrum
          - network: mainnet
    steps:
      - uses: actions/checkout@v2
      - name: Install node
        uses: actions/setup-node@v1
        with:
          node-version: 14
      - name: Install
        run: yarn --frozen-lockfile
      - name: Prepare
        env:
          NETWORK: ${{ matrix.network }}
        run: yarn prepare:$NETWORK
      - name: Codegen
        env:
          NETWORK: ${{ matrix.network }}
        run: yarn codegen:$NETWORK
      - name: Test
        run: yarn test
      - name: Build
        env:
          NETWORK: ${{ matrix.network }}
        run: yarn build:$NETWORK
      - name: Authenticate
        env:
          GRAPH_ACCESS_TOKEN: ${{ secrets.GRAPH_ACCESS_TOKEN }}
        run: yarn graph auth --product hosted-service "$GRAPH_ACCESS_TOKEN"
      - name: Deploy to production
        run: yarn deploy:prod
