name: Deploy Graph
on:
  workflow_dispatch:
    inputs:
      environment:
        type: environment
        description: Select environment
      subgraph:
        type: choice
        description: Select subgraph
        options:
        - bridgeworld
        - bridgeworld-approvals
        - bridgeworld-corruption
        - bridgeworld-kote
        - bridgeworld-recruits
        - magicswap-exchange
        - smol
      version:
        description: Subgraph version
        required: true
jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./subgraphs/${{ inputs.subgraph }}
    steps:
      - name: Check out code
        uses: actions/checkout@v2
      - name: Install Node
        uses: actions/setup-node@v1
        with:
          node-version: 18
      - name: Install dependencies
        run: yarn --frozen-lockfile
      - name: Prepare for DEV
        if: inputs.environment == 'Development'
        run: yarn prepare:dev
      - name: Prepare for PROD
        if: inputs.environment == 'Production'
        run: yarn prepare:prod
      - name: Generate code
        run: yarn codegen
      - name: Test
        run: yarn test
      - name: Deploy to DEV
        if: inputs.environment == 'Development'
        run: yarn graph deploy ${{ inputs.subgraph }}-dev --version-label ${{ inputs.version }} --node https://subgraphs.alchemy.com/api/subgraphs/deploy --ipfs https://ipfs.satsuma.xyz --deploy-key ${{ secrets.SATSUMA_DEPLOY_KEY }}
      - name: Deploy to PROD
        if: inputs.environment == 'Production'
        run: yarn graph deploy ${{ inputs.subgraph }} --version-label ${{ inputs.version }} --node https://subgraphs.alchemy.com/api/subgraphs/deploy --ipfs https://ipfs.satsuma.xyz --deploy-key ${{ secrets.SATSUMA_DEPLOY_KEY }}
